name:  flippy-N1

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  schedule:
    - cron:  '40 15 * * 4'
  watch:
    types: started

jobs:
  flippy-N1:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Init Building Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        echo "Init Building:$(date +%F_%H%M%S)"
        sudo -E swapoff -a
        docker rmi $(docker images -q) 
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android /opt/ghc /swapfile /etc/apt/sources.list.d
        sudo -E apt-get remove -y --purge azure-cli ghc zulu* hhvm llvm* firefox google* dotnet* powershell mysql* php* mssql-tools msodbcsql17 android*
        sudo -E apt-get update -y 
        sudo -E apt-get full-upgrade -y 
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804) rdate ca-certificates
        sudo -E apt-get autoremove -y --purge 
        sudo -E apt-get clean -y 
        
    - name: Show system
      run: |
        echo -e "Total CPU cores\t: $(nproc)"
        cat /proc/cpuinfo | grep 'model name'
        free -h
        uname -a
        [ -f /proc/version ] && cat /proc/version
        [ -f /etc/issue.net ] && cat /etc/issue.net
        [ -f /etc/issue ] && cat /etc/issue
        ulimit -a
        
    - name: Clone Source
      run: |
        echo "Clone Source":$(date +%F_%H%M%S)
        df -hP
        sudo mkdir -pv /build/{package,upload,buildinfo}
        sudo chown -R runner:runner /build
        git clone https://github.com/coolsnowwolf/lede.git /build/lede
        git clone https://github.com/unifreq/openwrt_packit.git /build/openwrt_packit
        cd /build/lede
        echo "src-git helloworld https://github.com/fw876/helloworld.git" >> feeds.conf.default
        echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall" >> feeds.conf.default
        echo "#src-git kenzo https://github.com/kenzok8/openwrt-packages" >> feeds.conf.default
        cat -n feeds.conf.default      
        rm -rf tmp/
        cd package/lean/
        rm -rf luci-theme-argon
        git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git
        git clone https://github.com/jerrykuku/lua-maxminddb.git
        git clone https://github.com/jerrykuku/luci-app-vssr.git
        git clone --depth=1 https://github.com/rufengsuixing/luci-app-onliner
        git clone --depth=1 -b master https://github.com/vernesong/OpenClash
        svn co https://github.com/zxlhhyccc/luci-app-v2raya/trunk/ luci-app-v2raya/
        svn co https://github.com/immortalwrt/packages/trunk/net/v2raya/ v2raya/
        cd /build/lede
        sh -c "./scripts/feeds update -a && ./scripts/feeds install -a"
        wget -O /build/lede/N1-openwrt.buildinfo https://raw.githubusercontent.com/we2oxy/Build-Lede/master/buildinfo/N1-openwrt.buildinfo
        cat /build/lede/N1-openwrt.buildinfo > "/build/lede/.config"
    - name: Configuration Customization
      id: configuration
      run: |
        echo "Configuration Customization":$(date +%F_%H%M%S)
        # system
        sed -i 's/luci-theme-bootstrap/luci-theme-argon/' /build/lede/feeds/luci/collections/luci/Makefile
        cat /build/lede/feeds/luci/collections/luci/Makefile
        sed -i '$d' /build/lede/package/lean/default-settings/files/zzz-default-settings
        sed -i '/DISTRIB_REVISION/d' /build/lede/package/lean/default-settings/files/zzz-default-settings
        sed -i '/DISTRIB_DESCRIPTION/d' /build/lede/package/lean/default-settings/files/zzz-default-settings
        cat $GITHUB_WORKSPACE/uciconf/lede-master/lede-master_settings >> /build/lede/package/lean/default-settings/files/zzz-default-settings
        sed -i 's/10.0.0.199/10.0.0.223/g' /build/lede/package/lean/default-settings/files/zzz-default-settings
        sed -i '/CYXluq4wUazHjmCDBCqXF/d'  /build/lede/package/lean/default-settings/files/zzz-default-settings
        cat /build/lede/package/lean/default-settings/files/zzz-default-settings
        sed -i 's,-SNAPSHOT,,g' /build/lede/include/version.mk
        sed -i 's,-SNAPSHOT,,g' /build/lede/package/base-files/image-config.in
        svn co https://github.com/we2oxy/OpenWrtConfig/trunk/files/etc /build/lede/files/etc
        cp -R /build/lede/files/etc/ssrplus/ /build/lede/files/etc/vssr/
        rm -rf /build/lede/files/etc/.svn/
        ls -lahR /build/lede/files/
        # luci-app-vssr
        sed -i '/result.encrypt_method/a\        result.fast_open = "1"' /build/lede/package/lean/luci-app-vssr/root/usr/share/vssr/subscribe.lua
        sed -i 's,ispip.clang.cn/all_cn.txt,cdn.jsdelivr.net/gh/QiuSimons/Chnroute@master/dist/chnroute/chnroute.txt,g' /build/lede/package/lean/luci-app-vssr/luasrc/controller/vssr.lua
        sed -i 's,ispip.clang.cn/all_cn.txt,cdn.jsdelivr.net/gh/QiuSimons/Chnroute@master/dist/chnroute/chnroute.txt,g' /build/lede/package/lean/luci-app-vssr/root/usr/share/vssr/update.lua
        # luci-app-ssr-plus
        rm -rf  /build/lede/feeds/helloworld/luci-app-ssr-plus/po/zh_Hans
        sed -i '/result.encrypt_method/a\                result.fast_open = "1"' /build/lede/feeds/helloworld/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
        sed -i 's,ispip.clang.cn/all_cn,cdn.jsdelivr.net/gh/QiuSimons/Chnroute@master/dist/chnroute/chnroute.txt,' /build/lede/feeds/helloworld/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
        sed -i 's,YW5vbnltb3Vz/domain-list-community/release/gfwlist.txt,Loyalsoldier/v2ray-rules-dat/release/gfw.txt,'  /build/lede/feeds/helloworld/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
        sed -i '/Clang.CN.CIDR/a\o:value("https://cdn.jsdelivr.net/gh/QiuSimons/Chnroute@master/dist/chnroute/chnroute.txt", translate("QiuSimons/Chnroute"))\' /build/lede/feeds/helloworld/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/advanced.lua
        
    - name: Configuration openwrt_packit
      id: openwrtpackit
      run: |
        echo "Configuration Customization":$(date +%F_%H%M%S)
        mv /build/openwrt_packit/make.env /build/openwrt_packit/make.envbak
        cp $GITHUB_WORKSPACE/uciconf/Phicomm_N1/make.env /build/openwrt_packit/make.env
        cp $GITHUB_WORKSPACE/uciconf/Phicomm_N1/*.gz /build/openwrt_packit/
        sed -i "N;10aOPENWRT_VER='$(date +%F)'" /build/openwrt_packit/make.env
        cat /build/openwrt_packit/make.env
        mkdir /build/openwrt_packit/Build_scripts_bak
        cp /build/openwrt_packit/mk_s905d_n1.sh /build/openwrt_packit/build_s905d_n1.sh
        mv /build/openwrt_packit/mk*.sh /build/openwrt_packit/Build_scripts_bak/
        ls -lh /build/openwrt_packit/
        ls -lh /build/openwrt_packit/Build_scripts_bak/
      
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        
    - name: Defconfig
      id: defconfig
      run: |
        echo "Build lede":$(date +%F_%H%M%S)
        cd /build/lede/ && ls -lash
        time make defconfig
        time make -j8 download || time make -j1 download || time make -j1 download V=s 
        ./scripts/diffconfig.sh > /build/buildinfo/N1-openwrt.buildinfo
        wc -l /build/buildinfo/N1-openwrt.buildinfo
        cat /build/buildinfo/N1-openwrt.buildinfo
        echo "########################################"
        ls -lh /build/buildinfo/

    - name: Deliver buildinfo
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: OpenWrt_buildinfo
        path: /build/buildinfo/
        if-no-files-found: ignore
        
    - name: Compile
      id: tools
      run: |
        cd /build/lede/
        echo -e "$(nproc) thread compile"
        time make tools/compile -j$(nproc) || time make tools/compile -j1 V=s
        time make toolchain/compile -j$(nproc) || time make toolchain/compile -j1 V=s
        time make target/compile -j$(nproc) || time make target/compile -j1 V=s IGNORE_ERRORS=1
        time make diffconfig
        time make package/compile -j$(nproc) IGNORE_ERRORS=1 || time make package/compile -j1 V=s IGNORE_ERRORS=1
        time make package/index

    - name: Generate Firmware
      id: generate
      run: |
        cd /build/lede/
        echo -e "$(nproc) thread compile"
        time make package/install -j$(nproc) || time make package/install -j1 V=s
        time make target/install -j$(nproc) || time make target/install -j1 V=s
        time make checksum
        tree bin/
        tree -d bin/
        cd /build/lede/bin/targets/armvirt/64 && ls -lSha
          
    - name: Prepare artifact
      run: |
        rm -rf $(find /build/lede/bin/targets/ -type d -name "packages")
        cp -rf $(find /build/lede/bin/targets/ -type f) /build/upload/
        cp -rf $(find /build/lede/bin/packages/ -type f -name "*.ipk") /build/package/
        cd /build/ && zip -qr /build/upload/package_$(date +%F_%H%M%S).zip package/
        cd /build/upload/
        ls -lh 
        cd /build/lede/
        tar -czf /build/lede-dl_$(date +%F_%H%M%S).tar.gz dl/
        ls -lhas /build/
        
    - name: mk s905d n1
      run: |
        cp /build/lede/bin/targets/armvirt/64/openwrt-armvirt-64-default-rootfs.tar.gz /build/openwrt_packit/
        cd /build/openwrt_packit
        sudo bash build_s905d_n1.sh
        sudo ls -lash tmp/
        #sudo gzip -9 tmp/*.img
        #sudo cp tmp/* /build/upload/
        sudo cp /build/openwrt_packit/output/* /build/upload/
        sudo ls -lash /build/openwrt_packit/output/ /build/upload/
        
    - name: Deliver firmware
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: OpenWrt_firmware
        path: /build/upload/
        if-no-files-found: ignore
        
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::$(date +%F_%H%M%S)_OpenWrt-Phicomm_N1"
        echo "::set-output name=release_date::$(date +"%F_%H%M%S")"
        touch release.txt
        echo "http://10.0.0.223" > release.txt
        echo "PASSWD = 'password'" >> release.txt
        #echo "::set-output name=status::success"
        echo "::set-output name=TAG_STATUS::success"
        
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v0.1.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ steps.tag.outputs.release_date }}_OpenWrt-Phicomm_N1
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: |
          /build/upload/*
        
    - name: Deliver dl
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: OpenWrt_dl
        path: /build/lede-dl*.tar.gz
        if-no-files-found: ignore